# fly.toml app configuration file generated for job-finder-super on 2026-05-28T19:11:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'job-finder-super'
primary_region = 'dfw'

[build]
  dockerfile = 'Dockerfile'

[env]
  CLIENT_DIST_DIR = '/app/client/dist'
  CACHE_SEED_MODE = 'overwrite'
  NODE_ENV = 'production'
  PORT = '8080'

[[mounts]]
  source = 'cache_data'
  destination = '/app/server/cache'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '40s'
    method = 'GET'
    path = '/api/hello'

[[vm]]
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 4096
